export const AboutMockData = {
  head: {
    pageTitle: '',
    metaDescription: '',
    imageOpenGraph: '',
    headScripts: '',
  },
  body: {
    bodyScripts: '',
  },
  banner: {
    titulo: '',
    subtitulo: '',
    descricao: '',
    imagem: '',
    url: '',
    id: 0,
    ativo: false,
    dataCriacao: '',
    dataEdicao: '',
  },
  tituloSessao1: '',
  textoSessao1: '',
  tituloBox1: '',
  subtituloBox1: '',
  textoBox1: '',
  tituloBox2: '',
  subtituloBox2: '',
  textoBox2: '',
  tituloBox3: '',
  textoBox3: '',
  imagem1: '',
  imagem2: '',
  tituloSessaoVideo: '',
  textoSessaoVideo: '',
  botaoSessaoVideo: '',
  link: '',
  tituloSessao2: '',
  textoSessao2: '',
  papeisProduzidos: '',
  clientesSatisfeitos: '',
};
