export const HomeMockData = {
  head: {
    pageTitle: '',
    metaDescription: '',
    imageOpenGraph: '',
    headScripts: '',
  },
  body: {
    bodyScripts: '',
  },
  banner: {
    video: '',
    link: '',
    titulo: '',
    descricao: '',
    imagem: '',
    thumbnail: '',
    url: '',
    id: 0,
    ativo: false,
    dataCriacao: '',
    dataEdicao: '',
  },
  papeisProduzidos: '',
  tituloCampanha: '',
  campanhas: '',
  nossasCampanhas: [
    {
      titulo: '',
      subtitulo: '',
      descricao: '',
      imagem: '',
      pageTitle: '',
      metaDescription: '',
      url: '',
      id: 0,
      ativo: false,
      dataCriacao: '',
      dataEdicao: '',
    },
    {
      titulo: '',
      subtitulo: '',
      descricao: '',
      imagem: '',
      pageTitle: '',
      metaDescription: '',
      url: '',
      id: 0,
      ativo: false,
      dataCriacao: '',
      dataEdicao: '',
    },
    {
      titulo: '',
      descricao: '',
      imagem: '',
      pageTitle: '',
      metaDescription: '',
      url: '',
      id: 0,
      ativo: false,
      dataCriacao: '',
      dataEdicao: '',
    },
  ],
  tituloSessaoVideo: '',
  textoSessaoVideo: '',
  i9Blog: '',
  blogs: [
    {
      categoriaTitle: '',
      categoriaId: '',
      titulo: '',
      subtitulo: '',
      descricao: '',
      imagem: '',
      url: '',
      id: 0,
    },
  ],
  imagem: '',
  subtituloBanner: '',
  tituloBanner2: '',
  sustentabilidade: '',
  tituloProduto: '',
  subtituloProduto: '',
  produto: '',
  produtoSubtitulo: '',
  produtoNome: '',
  produtoImagem: '',
  produtoBotao: '',
};
