export const ShopMockData = {
  id: 0,
  pageTotal: 35,
  pageSize: 300,
  pageNumber: 1,
  hasNextPage: false,
  hasPreviousPage: false,
  isFirstPage: true,
  isLastPage: true,
  items: [
    {
      id: 4,
      titulo: 'lorem titulo',
      telefone: '17-3631-2942',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP',
    },
    {
      id: 5,
      titulo: 'lorem titulo',
      telefone: '14 3433-7479',
      categoriaId: 0,
      cidade: ' Marília - SP',
    },
    {
      id: 6,
      titulo: 'lorem titulo',
      telefone: '14-3377-1344',
      categoriaId: 0,
      cidade: 'São Pedro do Turvo - SP',
    },
    {
      id: 7,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Ilha Solteira - SP',
    },
    {
      id: 8,
      titulo: 'lorem titulo',
      telefone: '17 3837-1227',
      categoriaId: 0,
      cidade: 'Sebastianopolis do Sul - SP',
    },
    {
      id: 9,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Jales - SP ',
    },
    {
      id: 10,
      titulo: 'lorem titulo',
      telefone: '14 3026-3771',
      categoriaId: 0,
      cidade: 'Ourinhos - SP',
    },
    {
      id: 11,
      titulo: 'lorem titulo',
      telefone: '17 3631-1468',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP  ',
    },
    {
      id: 12,
      titulo: 'lorem titulo',
      telefone: '18 3305-9044',
      categoriaId: 0,
      cidade: 'Araçatuba - SP',
    },
    {
      id: 13,
      titulo: 'lorem titulo',
      telefone: '17 3421-2323',
      categoriaId: 0,
      cidade: 'Votuporanga - SP',
    },
    {
      id: 14,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Ouro Verde - SP',
    },
    {
      id: 15,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Cerqueira Cesar - SP',
    },
    {
      id: 16,
      titulo: 'lorem titulo',
      telefone: '14 3541-5777',
      categoriaId: 0,
      cidade: 'Promissão - SP',
    },
    {
      id: 17,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP',
    },
    {
      id: 18,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Adamantina - SP ',
    },
    {
      id: 19,
      titulo: 'lorem titulo',
      telefone: '16 3251-4020',
      categoriaId: 0,
      cidade: 'Guariba - SP',
    },
    {
      id: 20,
      titulo: 'lorem titulo',
      telefone: '17 3633-1607',
      categoriaId: 0,
      cidade: 'Santa Albertina - SP',
    },
    {
      id: 21,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Santa Cruz Do Rio Pardo - SP',
    },
    {
      id: 22,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Dracena - SP',
    },
    {
      id: 23,
      titulo: 'lorem titulo',
      telefone: '14 33722-2074',
      categoriaId: 0,
      cidade: 'Santa Cruz Do Rio Pardo - SP',
    },
    {
      id: 24,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Marilia - SP',
    },
    {
      id: 25,
      titulo: 'lorem titulo',
      telefone: '16 3251-1011',
      categoriaId: 0,
      cidade: 'Guariba - SP',
    },
    {
      id: 26,
      titulo: 'lorem titulo',
      telefone: '18 3406-2016',
      categoriaId: 0,
      cidade: 'Guararapes - SP',
    },
    {
      id: 27,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Monte alto - SP',
    },
    {
      id: 28,
      titulo: 'lorem titulo',
      telefone: '14 3238-6200',
      categoriaId: 0,
      cidade: 'Bauru - SP',
    },
    {
      id: 29,
      titulo: 'lorem titulo',
      telefone: '17 3691-1552',
      categoriaId: 0,
      cidade: 'Três Fronteiras - SP',
    },
    {
      id: 30,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Tambau - SP',
    },
    {
      id: 31,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Assis - SP',
    },
    {
      id: 32,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Tabatinga - SP',
    },
    {
      id: 33,
      titulo: 'lorem titulo',
      telefone: '17 3445-7570',
      categoriaId: 0,
      cidade: 'Americo de Campos - SP',
    },
    {
      id: 34,
      titulo: 'lorem titulo',
      telefone: '19 3594-6466',
      categoriaId: 0,
      cidade: 'Descalvado - SP',
    },
    {
      id: 35,
      titulo: 'lorem titulo',
      telefone: '--------------',
      categoriaId: 0,
      cidade: 'Espirito Santo do Turvo - SP',
    },
    {
      id: 36,
      titulo: 'lorem titulo',
      telefone: '17 3631-2942',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP',
    },
    {
      id: 37,
      titulo: 'lorem titulo',
      telefone: '17 3641-2070',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP',
    },
    {
      id: 38,
      titulo: 'lorem titulo',
      telefone: '17 3631-2670 ',
      categoriaId: 0,
      cidade: 'Santa Fé Do Sul - SP',
    },
  ],
};
